<?php
/*
	Copyright 2011 John Mullee

	This file is part of PhpUnixDaemon.

	PhpUnixDaemon is free software: you can redistribute it and/or modify it under the terms of the
	GNU General Public License as published by the Free Software Foundation, either version 3 of
	the License, or (at your option) any later version.

	PhpUnixDaemon is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with PhpUnixDaemon.
	If not, see http://www.gnu.org/licenses/.
*/

# generated by './generate_signal_php.sh' on Wed Aug  3 18:30:30 IST 2011
if(!defined('SIGABRT'))	define('SIGABRT',6);
if(!defined('SIGALRM'))	define('SIGALRM',14);
if(!defined('SIGBUS'))	define('SIGBUS',7);
if(!defined('SIGCHLD'))	define('SIGCHLD',17);
if(!defined('SIGCONT'))	define('SIGCONT',18);
if(!defined('SIGFPE'))	define('SIGFPE',8);
if(!defined('SIGHUP'))	define('SIGHUP',1);
if(!defined('SIGILL'))	define('SIGILL',4);
if(!defined('SIGINT'))	define('SIGINT',2);
if(!defined('SIGIO'))	define('SIGIO',29);
if(!defined('SIGIOT'))	define('SIGIOT',6);
if(!defined('SIGKILL'))	define('SIGKILL',9);
if(!defined('SIGLOST'))	define('SIGLOST',29);
if(!defined('SIGPIPE'))	define('SIGPIPE',13);
if(!defined('SIGPROF'))	define('SIGPROF',27);
if(!defined('SIGPWR'))	define('SIGPWR',30);
if(!defined('SIGQUIT'))	define('SIGQUIT',3);
if(!defined('SIGRTMIN'))	define('SIGRTMIN',32);
if(!defined('SIGSEGV'))	define('SIGSEGV',11);
if(!defined('SIGSTKFLT'))	define('SIGSTKFLT',16);
if(!defined('SIGSTKSZ'))	define('SIGSTKSZ',8192);
if(!defined('SIGSTOP'))	define('SIGSTOP',19);
if(!defined('SIGSYS'))	define('SIGSYS',31);
if(!defined('SIGTERM'))	define('SIGTERM',15);
if(!defined('SIGTRAP'))	define('SIGTRAP',5);
if(!defined('SIGTSTP'))	define('SIGTSTP',20);
if(!defined('SIGTTIN'))	define('SIGTTIN',21);
if(!defined('SIGTTOU'))	define('SIGTTOU',22);
if(!defined('SIGURG'))	define('SIGURG',23);
if(!defined('SIGUSR1'))	define('SIGUSR1',10);
if(!defined('SIGUSR2'))	define('SIGUSR2',12);
if(!defined('SIGVTALRM'))	define('SIGVTALRM',26);
if(!defined('SIGWINCH'))	define('SIGWINCH',28);
if(!defined('SIGXCPU'))	define('SIGXCPU',24);
if(!defined('SIGXFSZ'))	define('SIGXFSZ',25);
